name: gaussian_splatting
channels:
- conda-forge
- nvidia
- pytorch
- pytorch3d
dependencies:
- _libgcc_mutex=0.1=conda_forge
- _openmp_mutex=4.5=2_kmp_llvm
- absl-py=2.1.0=pyhd8ed1ab_0
- alsa-lib=1.2.10=hd590300_0
- aom=3.7.1=h59595ed_0
- asttokens=2.4.0=pyhd8ed1ab_0
- attr=2.5.1=h166bdaf_1
- attrs=23.2.0=pyh71513ae_0
- backcall=0.2.0=pyh9f0ad1d_0
- backports=1.0=pyhd8ed1ab_3
- backports.functools_lru_cache=1.6.5=pyhd8ed1ab_0
- binutils_impl_linux-64=2.40=hf600244_0
- binutils_linux-64=2.40=hbdbef99_2
- blas=2.116=mkl
- blas-devel=3.9.0=16_linux64_mkl
- brotli=1.1.0=hd590300_1
- brotli-bin=1.1.0=hd590300_1
- brotli-python=1.1.0=py311hb755f60_1
- bzip2=1.0.8=h7f98852_4
- c-ares=1.21.0=hd590300_0
- ca-certificates=2023.7.22=hbcca054_0
- cairo=1.18.0=h3faef2a_0
- cattrs=23.2.3=pyhd8ed1ab_0
- certifi=2023.7.22=pyhd8ed1ab_0
- charset-normalizer=3.3.0=pyhd8ed1ab_0
- colorama=0.4.6=pyhd8ed1ab_0
- comm=0.1.4=pyhd8ed1ab_0
- contourpy=1.1.1=py311h9547e67_1
- cuda-cudart=12.1.105=0
- cuda-cupti=12.1.105=0
- cuda-libraries=12.1.0=0
- cuda-nvrtc=12.1.105=0
- cuda-nvtx=12.1.105=0
- cuda-opencl=12.3.52=0
- cuda-runtime=12.1.0=0
- cuda-version=11.8=h70ddcb2_2
- cudatoolkit=11.8.0=h4ba93d1_12
- cudnn=8.8.0.121=h838ba91_3
- cycler=0.12.1=pyhd8ed1ab_0
- dataclasses=0.8=pyhc8e2a94_3
- dav1d=1.2.1=hd590300_0
- dbus=1.13.6=h5008d03_3
- debugpy=1.8.0=py311hb755f60_1
- decorator=5.1.1=pyhd8ed1ab_0
- docstring-to-markdown=0.14=pyhd8ed1ab_0
- exceptiongroup=1.1.3=pyhd8ed1ab_0
- executing=1.2.0=pyhd8ed1ab_0
- expat=2.5.0=hcb278e6_1
- ffmpeg=6.1.0=gpl_h402741f_101
- filelock=3.12.4=pyhd8ed1ab_0
- font-ttf-dejavu-sans-mono=2.37=hab24e00_0
- font-ttf-inconsolata=3.000=h77eed37_0
- font-ttf-source-code-pro=2.038=h77eed37_0
- font-ttf-ubuntu=0.83=hab24e00_0
- fontconfig=2.14.2=h14ed4e7_0
- fonts-conda-ecosystem=1=0
- fonts-conda-forge=1=0
- fonttools=4.43.1=py311h459d7ec_0
- freeglut=3.2.2=hac7e632_2
- freetype=2.12.1=h267a509_2
- fribidi=1.0.10=h36c2ea0_0
- fvcore=0.1.5.post20221221=pyhd8ed1ab_0
- gcc_impl_linux-64=13.2.0=h338b0a0_3
- gcc_linux-64=13.2.0=h112eaf3_2
- gettext=0.21.1=h27087fc_0
- glib=2.78.0=hfc55251_0
- glib-tools=2.78.0=hfc55251_0
- gmp=6.3.0=h59595ed_0
- gmpy2=2.1.2=py311h6a5fa03_1
- gnutls=3.7.9=hb077bed_0
- graphite2=1.3.13=h58526e2_1001
- grpcio=1.58.1=py311ha6695c7_2
- gst-plugins-base=1.22.6=h8e1006c_2
- gstreamer=1.22.6=h98fc4e7_2
- gxx_impl_linux-64=13.2.0=h338b0a0_3
- gxx_linux-64=13.2.0=hc53e3bf_2
- harfbuzz=8.2.1=h3d44ed6_0
- hdf5=1.14.2=nompi_h4f84152_100
- icecream=2.1.3=pyhd8ed1ab_0
- icu=73.2=h59595ed_0
- idna=3.4=pyhd8ed1ab_0
- imageio=2.31.5=pyh8c1a49c_0
- importlib-metadata=6.8.0=pyha770c72_0
- importlib_metadata=6.8.0=hd8ed1ab_0
- iopath=0.1.9=pyhd8ed1ab_0
- ipykernel=6.26.0=pyhf8b6a83_0
- ipympl=0.9.3=pyhd8ed1ab_0
- ipython=8.16.1=pyh0d859eb_0
- ipython_genutils=0.2.0=py_1
- ipywidgets=8.1.1=pyhd8ed1ab_0
- jasper=4.1.0=he6dfbbe_0
- jax=0.4.19=pyhd8ed1ab_0
- jaxlib=0.4.19=cuda118py311h045a74e_200
- jedi=0.19.1=pyhd8ed1ab_0
- jedi-language-server=0.41.2=pyhd8ed1ab_0
- jinja2=3.1.2=pyhd8ed1ab_1
- jupyter_client=8.5.0=pyhd8ed1ab_0
- jupyter_core=5.4.0=py311h38be061_0
- jupyterlab_widgets=3.0.9=pyhd8ed1ab_0
- kernel-headers_linux-64=2.6.32=he073ed8_16
- keyutils=1.6.1=h166bdaf_0
- kiwisolver=1.4.5=py311h9547e67_1
- kornia=0.7.0=pyhd8ed1ab_0
- krb5=1.21.2=h659d440_0
- lame=3.100=h166bdaf_1003
- lcms2=2.15=hb7c19ff_3
- ld_impl_linux-64=2.40=h41732ed_0
- lerc=4.0.0=h27087fc_0
- libabseil=20230802.1=cxx17_h59595ed_0
- libaec=1.1.2=h59595ed_1
- libass=0.17.1=h8fe9dca_1
- libblas=3.9.0=16_linux64_mkl
- libbrotlicommon=1.1.0=hd590300_1
- libbrotlidec=1.1.0=hd590300_1
- libbrotlienc=1.1.0=hd590300_1
- libcap=2.69=h0f662aa_0
- libcblas=3.9.0=16_linux64_mkl
- libclang=15.0.7=default_h7634d5b_3
- libclang13=15.0.7=default_h9986a30_3
- libcublas=12.1.0.26=0
- libcufft=11.0.2.4=0
- libcufile=1.8.0.34=0
- libcups=2.3.3=h4637d8d_4
- libcurand=10.3.4.52=0
- libcurl=8.4.0=hca28451_0
- libcusolver=11.4.4.55=0
- libcusparse=12.0.2.55=0
- libdeflate=1.19=hd590300_0
- libdrm=2.4.114=h166bdaf_0
- libedit=3.1.20191231=he28a2e2_2
- libev=4.33=hd590300_2
- libevent=2.1.12=hf998b51_1
- libexpat=2.5.0=hcb278e6_1
- libffi=3.4.2=h7f98852_5
- libflac=1.4.3=h59595ed_0
- libgcc-devel_linux-64=13.2.0=ha9c7c90_103
- libgcc-ng=13.2.0=h807b86a_2
- libgcrypt=1.10.1=h166bdaf_0
- libgfortran-ng=13.2.0=h69a702a_2
- libgfortran5=13.2.0=ha4646dd_2
- libglib=2.78.0=hebfc3b9_0
- libglu=9.0.0=hac7e632_1003
- libgomp=13.2.0=h807b86a_2
- libgpg-error=1.47=h71f35ed_0
- libgrpc=1.58.1=he06187c_2
- libhwloc=2.9.3=default_h554bfaf_1009
- libiconv=1.17=h166bdaf_0
- libidn2=2.3.4=h166bdaf_0
- libjpeg-turbo=3.0.0=hd590300_1
- liblapack=3.9.0=16_linux64_mkl
- liblapacke=3.9.0=16_linux64_mkl
- libllvm15=15.0.7=h5cf9203_3
- libnghttp2=1.52.0=h61bc06f_0
- libnpp=12.0.2.50=0
- libnsl=2.0.1=hd590300_0
- libnvjitlink=12.1.105=0
- libnvjpeg=12.1.1.14=0
- libogg=1.3.4=h7f98852_1
- libopencv=4.8.1=py311h60c0964_4
- libopenvino=2023.1.0=h59595ed_2
- libopenvino-auto-batch-plugin=2023.1.0=h59595ed_2
- libopenvino-auto-plugin=2023.1.0=h59595ed_2
- libopenvino-hetero-plugin=2023.1.0=h59595ed_2
- libopenvino-intel-cpu-plugin=2023.1.0=h59595ed_2
- libopenvino-intel-gpu-plugin=2023.1.0=h59595ed_2
- libopenvino-ir-frontend=2023.1.0=h59595ed_2
- libopenvino-onnx-frontend=2023.1.0=h59595ed_2
- libopenvino-paddle-frontend=2023.1.0=h59595ed_2
- libopenvino-pytorch-frontend=2023.1.0=h59595ed_2
- libopenvino-tensorflow-frontend=2023.1.0=h59595ed_2
- libopenvino-tensorflow-lite-frontend=2023.1.0=h59595ed_2
- libopus=1.3.1=h7f98852_1
- libpciaccess=0.17=h166bdaf_0
- libpng=1.6.39=h753d276_0
- libpq=16.0=hfc447b1_1
- libprotobuf=4.24.3=hf27288f_1
- libre2-11=2023.06.02=h7a70373_0
- libsanitizer=13.2.0=h7e041cc_3
- libsndfile=1.2.2=hc60ed4a_1
- libsodium=1.0.18=h36c2ea0_1
- libsqlite=3.43.2=h2797004_0
- libssh2=1.11.0=h0841786_0
- libstdcxx-devel_linux-64=13.2.0=ha9c7c90_103
- libstdcxx-ng=13.2.0=h7e041cc_2
- libsystemd0=254=h3516f8a_0
- libtasn1=4.19.0=h166bdaf_0
- libtiff=4.6.0=ha9c0a0a_2
- libunistring=0.9.10=h7f98852_0
- libuuid=2.38.1=h0b41bf4_0
- libva=2.20.0=hd590300_0
- libvorbis=1.3.7=h9c3ff4c_0
- libvpx=1.13.1=h59595ed_0
- libwebp-base=1.3.2=hd590300_0
- libxcb=1.15=h0b41bf4_0
- libxkbcommon=1.6.0=h5d7e998_0
- libxml2=2.11.5=h232c23b_1
- libzlib=1.2.13=hd590300_5
- llvm-openmp=15.0.7=h0cdce71_0
- lsprotocol=2023.0.1=pyhd8ed1ab_0
- lz4-c=1.9.4=hcb278e6_0
- markdown=3.5.2=pyhd8ed1ab_0
- markupsafe=2.1.3=py311h459d7ec_1
- matplotlib=3.8.0=py311h38be061_2
- matplotlib-base=3.8.0=py311h54ef318_2
- matplotlib-inline=0.1.6=pyhd8ed1ab_0
- mkl=2022.1.0=h84fe81f_915
- mkl-devel=2022.1.0=ha770c72_916
- mkl-include=2022.1.0=h84fe81f_915
- ml_dtypes=0.3.1=py311h320fe9a_2
- mpc=1.3.1=hfe3b2da_0
- mpfr=4.2.0=hb012696_0
- mpg123=1.32.3=h59595ed_0
- mpmath=1.3.0=pyhd8ed1ab_0
- munkres=1.1.4=pyh9f0ad1d_0
- mysql-common=8.0.33=hf1915f5_5
- mysql-libs=8.0.33=hca2cd23_5
- nccl=2.19.3.1=h6103f9b_0
- ncurses=6.4=hcb278e6_0
- nest-asyncio=1.5.8=pyhd8ed1ab_0
- nettle=3.9.1=h7ab15ed_0
- networkx=3.2=pyhd8ed1ab_1
- nspr=4.35=h27087fc_0
- nss=3.94=h1d7d5a4_0
- numpy=1.26.0=py311h64a7726_0
- ocl-icd=2.3.1=h7f98852_0
- ocl-icd-system=1.0.0=1
- openh264=2.3.1=hcb278e6_2
- openjpeg=2.5.0=h488ebb8_3
- openssl=3.1.3=hd590300_0
- opt-einsum=3.3.0=hd8ed1ab_2
- opt_einsum=3.3.0=pyhc1e730c_2
- p11-kit=0.24.1=hc5aa10d_0
- packaging=23.2=pyhd8ed1ab_0
- parso=0.8.3=pyhd8ed1ab_0
- pcre2=10.40=hc3806b6_0
- pexpect=4.8.0=pyh1a96a4e_2
- pickleshare=0.7.5=py_1003
- pillow=10.1.0=py311ha6c5da5_0
- pip=23.3=pyhd8ed1ab_0
- pixman=0.42.2=h59595ed_0
- platformdirs=3.11.0=pyhd8ed1ab_0
- ply=3.11=py_1
- plyfile=1.0.1=pyhd8ed1ab_0
- portalocker=2.8.2=py311h38be061_1
- prompt-toolkit=3.0.39=pyha770c72_0
- prompt_toolkit=3.0.39=hd8ed1ab_0
- protobuf=4.24.3=py311h46cbc50_1
- psutil=5.9.5=py311h459d7ec_1
- pthread-stubs=0.4=h36c2ea0_1001
- ptyprocess=0.7.0=pyhd3deb0d_0
- pugixml=1.14=h59595ed_0
- pulseaudio-client=16.1=hb77b528_5
- pure_eval=0.2.2=pyhd8ed1ab_0
- py-opencv=4.8.1=py311hcd063c8_4
- pygls=1.3.0=pyhd8ed1ab_0
- pygments=2.16.1=pyhd8ed1ab_0
- pyparsing=3.1.1=pyhd8ed1ab_0
- pyqt=5.15.9=py311hf0fb5b6_5
- pyqt5-sip=12.12.2=py311hb755f60_5
- pysocks=1.7.1=pyha2e5f31_6
- python=3.11.6=hab00c5b_0_cpython
- python-dateutil=2.8.2=pyhd8ed1ab_0
- python_abi=3.11=4_cp311
- pytorch=2.1.0=py3.11_cuda12.1_cudnn8.9.2_0
- pytorch-cuda=12.1=ha16c6d3_5
- pytorch-mutex=1.0=cuda
- pytorch3d=0.7.5=py311_cu121_pyt210
- pyyaml=6.0.1=py311h459d7ec_1
- pyzmq=25.1.1=py311h34ded2d_2
- qt-main=5.15.8=h82b777d_17
- re2=2023.06.02=h2873b5e_0
- readline=8.2=h8228510_1
- requests=2.31.0=pyhd8ed1ab_0
- scipy=1.11.3=py311h64a7726_1
- setuptools=68.2.2=pyhd8ed1ab_0
- sip=6.7.12=py311hb755f60_0
- six=1.16.0=pyh6c4a22f_0
- snappy=1.1.10=h9fff704_0
- stack_data=0.6.2=pyhd8ed1ab_0
- svt-av1=1.7.0=h59595ed_0
- sympy=1.12=pypyh9d50eac_103
- sysroot_linux-64=2.12=he073ed8_16
- tabulate=0.9.0=pyhd8ed1ab_1
- tbb=2021.10.0=h00ab1b0_2
- tensorboard=2.16.2=pyhd8ed1ab_0
- tensorboard-data-server=0.7.0=py311h63ff55d_1
- termcolor=2.4.0=pyhd8ed1ab_0
- tk=8.6.13=h2797004_0
- toml=0.10.2=pyhd8ed1ab_0
- tomli=2.0.1=pyhd8ed1ab_0
- torchaudio=2.1.0=py311_cu121
- torchtriton=2.1.0=py311
- torchvision=0.16.0=py311_cu121
- tornado=6.3.3=py311h459d7ec_1
- tqdm=4.66.1=pyhd8ed1ab_0
- traitlets=5.12.0=pyhd8ed1ab_0
- typing-extensions=4.8.0=hd8ed1ab_0
- typing_extensions=4.8.0=pyha770c72_0
- tzdata=2023c=h71feb2d_0
- urllib3=2.0.7=pyhd8ed1ab_0
- wcwidth=0.2.8=pyhd8ed1ab_0
- werkzeug=3.0.1=pyhd8ed1ab_0
- wheel=0.41.2=pyhd8ed1ab_0
- widgetsnbextension=4.0.9=pyhd8ed1ab_0
- x264=1!164.3095=h166bdaf_2
- x265=3.5=h924138e_3
- xcb-util=0.4.0=hd590300_1
- xcb-util-image=0.4.0=h8ee46fc_1
- xcb-util-keysyms=0.4.0=h8ee46fc_1
- xcb-util-renderutil=0.3.9=hd590300_1
- xcb-util-wm=0.4.1=h8ee46fc_1
- xkeyboard-config=2.40=hd590300_0
- xorg-fixesproto=5.0=h7f98852_1002
- xorg-inputproto=2.3.2=h7f98852_1002
- xorg-kbproto=1.0.7=h7f98852_1002
- xorg-libice=1.1.1=hd590300_0
- xorg-libsm=1.2.4=h7391055_0
- xorg-libx11=1.8.7=h8ee46fc_0
- xorg-libxau=1.0.11=hd590300_0
- xorg-libxdmcp=1.1.3=h7f98852_0
- xorg-libxext=1.3.4=h0b41bf4_2
- xorg-libxfixes=5.0.3=h7f98852_1004
- xorg-libxi=1.7.10=h7f98852_0
- xorg-libxrender=0.9.11=hd590300_0
- xorg-renderproto=0.11.1=h7f98852_1002
- xorg-xextproto=7.3.0=h0b41bf4_1003
- xorg-xf86vidmodeproto=2.3.1=h7f98852_1002
- xorg-xproto=7.0.31=h7f98852_1007
- xz=5.2.6=h166bdaf_0
- yacs=0.1.8=pyhd8ed1ab_0
- yaml=0.2.5=h7f98852_2
- zeromq=4.3.5=h59595ed_0
- zipp=3.17.0=pyhd8ed1ab_0
- zlib=1.2.13=hd590300_5
- zstd=1.5.5=hfc55251_0

